# Generated by Django 3.2.25 on 2024-10-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registered_at',
            field=models.DateField(),
        ),
    ]
