# Generated by Django 3.2.25 on 2024-10-06 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20241006_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
