# Generated by Django 3.2.25 on 2024-10-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20241006_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='casualtyreport',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='casualtyreport',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
