# Generated by Django 3.2.25 on 2024-10-06 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20241006_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casualtyreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
