# Generated by Django 3.2.25 on 2024-10-06 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_casualtyreport_report_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casualtyreport',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='casualtyreport',
            name='name',
        ),
        migrations.AlterField(
            model_name='casualtyreport',
            name='report_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
