# Generated by Django 3.2.25 on 2024-10-06 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20241006_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='casualtyreport',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='casualtyreport',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='casualtyreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
